server:
  port: 8082
spring:
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      userCreated: USER_CREATED_TOPIC
  mail:
    host: smtp.gmail.com
    port: 587
    username: projects.management.app@gmail.com
    password: tomjan5554
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  application:
    name: mail-service
    cloud:
      config:
        discovery:
          enabled: true
          service-id: mail-service
    h2:
      console:
        enabled: true
        path: /h2-console
      datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
      topic:
        userCreated: USER_CREATED_TOPIC
    security:
      basic:
        enabled: false