server:
  port: 8081
spring:
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      userCreated: USER_CREATED_TOPIC
  application:
    name: user-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: user-service
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
  security:
    basic:
      enabled: true